# Assignment 2
To Classify the email using the binary classification method.  

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix,mean_absolute_error,mean_squared_error,r2_score

In [2]:
df=pd.read_csv("C:/Users/DELL/BE Computer/ML_Submission_19121033/ML_Submission_19121033/csvs/emails.csv")

In [3]:
df.head(3)

Email No.  the  to  ect  and  for  of    a  you  hou  ...  connevey  jay  \
0   Email 1    0   0    1    0    0   0    2    0    0  ...         0    0   
1   Email 2    8  13   24    6    6   2  102    1   27  ...         0    0   
2   Email 3    0   0    1    0    0   0    8    0    0  ...         0    0   

   valued  lay  infrastructure  military  allowing  ff  dry  Prediction  
0       0    0               0         0         0   0    0           0  
1       0    0               0         0         0   1    0           0  
2       0    0               0         0         0   0    0           0  

[3 rows x 3002 columns]

In [4]:
df.columns

Index(['Email No.', 'the', 'to', 'ect', 'and', 'for', 'of', 'a', 'you', 'hou',
       ...
       'connevey', 'jay', 'valued', 'lay', 'infrastructure', 'military',
       'allowing', 'ff', 'dry', 'Prediction'],
      dtype='object', length=3002)

In [5]:
df.shape

(5172, 3002)

In [6]:
df.size

15526344

In [7]:
df.isna().sum()

Email No.     0
the           0
to            0
ect           0
and           0
             ..
military      0
allowing      0
ff            0
dry           0
Prediction    0
Length: 3002, dtype: int64

In [8]:
df.isna().sum().sum()

0

In [9]:
df.describe()

the           to          ect          and          for  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000   
mean      6.640565     6.188128     5.143852     3.075599     3.124710   
std      11.745009     9.534576    14.101142     6.045970     4.680522   
min       0.000000     0.000000     1.000000     0.000000     0.000000   
25%       0.000000     1.000000     1.000000     0.000000     1.000000   
50%       3.000000     3.000000     1.000000     1.000000     2.000000   
75%       8.000000     7.000000     4.000000     3.000000     4.000000   
max     210.000000   132.000000   344.000000    89.000000    47.000000   

                of            a          you          hou           in  ...  \
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  ...   
mean      2.627030    55.517401     2.466551     2.024362    10.600155  ...   
std       6.229845    87.574172     4.314444     6.967878    19.281892  ...   
min       0.000000     0.000000     0.000000     0.000000     0.000000  ...   
25%       0.000000    12.000000     0.000000     0.000000     1.000000  ...   
50%       1.000000    28.000000     1.000000     0.000000     5.000000  ...   
75%       2.000000    62.250000     3.000000     1.000000    12.000000  ...   
max      77.000000  1898.000000    70.000000   167.000000   223.000000  ...   

          connevey          jay       valued          lay  infrastructure  \
count  5172.000000  5172.000000  5172.000000  5172.000000     5172.000000   
mean      0.005027     0.012568     0.010634     0.098028        0.004254   
std       0.105788     0.199682     0.116693     0.569532        0.096252   
min       0.000000     0.000000     0.000000     0.000000        0.000000   
25%       0.000000     0.000000     0.000000     0.000000        0.000000   
50%       0.000000     0.000000     0.000000     0.000000        0.000000   
75%       0.000000     0.000000     0.000000     0.000000        0.000000   
max       4.000000     7.000000     2.000000    12.000000        3.000000   

          military     allowing           ff          dry   Prediction  
count  5172.000000  5172.000000  5172.000000  5172.000000  5172.000000  
mean      0.006574     0.004060     0.914733     0.006961     0.290023  
std       0.138908     0.072145     2.780203     0.098086     0.453817  
min       0.000000     0.000000     0.000000     0.000000     0.000000  
25%       0.000000     0.000000     0.000000     0.000000     0.000000  
50%       0.000000     0.000000     0.000000     0.000000     0.000000  
75%       0.000000     0.000000     1.000000     0.000000     1.000000  
max       4.000000     3.000000   114.000000     4.000000     1.000000  

[8 rows x 3001 columns]

In [10]:
df['Prediction'].unique()

array([0, 1], dtype=int64)

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB

In [12]:
x=df.iloc[:,1:-1]

In [13]:
x

the  to  ect  and  for  of    a  you  hou  in  ...  enhancements  \
0       0   0    1    0    0   0    2    0    0   0  ...             0   
1       8  13   24    6    6   2  102    1   27  18  ...             0   
2       0   0    1    0    0   0    8    0    0   4  ...             0   
3       0   5   22    0    5   1   51    2   10   1  ...             0   
4       7   6   17    1    5   2   57    0    9   3  ...             0   
...   ...  ..  ...  ...  ...  ..  ...  ...  ...  ..  ...           ...   
5167    2   2    2    3    0   0   32    0    0   5  ...             0   
5168   35  27   11    2    6   5  151    4    3  23  ...             0   
5169    0   0    1    1    0   0   11    0    0   1  ...             0   
5170    2   7    1    0    2   1   28    2    0   8  ...             0   
5171   22  24    5    1    6   5  148    8    2  23  ...             0   

      connevey  jay  valued  lay  infrastructure  military  allowing  ff  dry  
0            0    0       0    0               0         0         0   0    0  
1            0    0       0    0               0         0         0   1    0  
2            0    0       0    0               0         0         0   0    0  
3            0    0       0    0               0         0         0   0    0  
4            0    0       0    0               0         0         0   1    0  
...        ...  ...     ...  ...             ...       ...       ...  ..  ...  
5167         0    0       0    0               0         0         0   0    0  
5168         0    0       0    0               0         0         0   1    0  
5169         0    0       0    0               0         0         0   0    0  
5170         0    0       0    0               0         0         0   1    0  
5171         0    0       0    0               0         0         0   0    0  

[5172 rows x 3000 columns]

In [14]:
y=df.iloc[:,-1]

In [15]:
y

0       0
1       0
2       0
3       0
4       0
       ..
5167    0
5168    0
5169    1
5170    1
5171    0
Name: Prediction, Length: 5172, dtype: int64

In [16]:
xtr,xte,ytr,yte=train_test_split(x,y,train_size=0.8)

# 1.NaiveBayes

In [17]:
NB_Classifier=MultinomialNB()

In [18]:
NB_Classifier.fit(xtr,ytr)

MultinomialNB()

In [19]:
ypred=NB_Classifier.predict(xte)

In [20]:
ypred

array([0, 0, 0, ..., 0, 0, 1], dtype=int64)

In [21]:
accuracy_score(yte,ypred)

0.9391304347826087

In [22]:
confusion_matrix(yte,ypred)

array([[698,  44],
       [ 19, 274]], dtype=int64)

In [23]:
mse=mean_squared_error(yte,ypred)
mae=mean_absolute_error(yte,ypred)
rmse=(mean_absolute_error(yte,ypred)**0.5)
r2=r2_score(yte,ypred)

In [24]:
print(mse)
print(mae)
print(rmse)
print(r2)

0.06086956521739131
0.06086956521739131
0.24671758189758447
0.7000772747762252


# 2.RandomClassiffier

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
#RF_Classifier=RandomForestClassifier(n_estimators=200,criterion='gini',random_state=0)
RF_Classifier=RandomForestClassifier()

In [27]:
RF_Classifier.fit(xtr,ytr)

RandomForestClassifier()

In [28]:
ypred2=RF_Classifier.predict(xte)

In [29]:
ypred2

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [30]:
accuracy_score(yte,ypred2)

0.9768115942028985

In [31]:
mse=mean_squared_error(yte,ypred2)
mae=mean_absolute_error(yte,ypred2)
rmse=(mean_absolute_error(yte,ypred2)**0.5)
r2=r2_score(yte,ypred2)

In [32]:
print(mse)
print(mae)
print(rmse)
print(r2)

0.02318840579710145
0.02318840579710145
0.1522773975253762
0.8857437237242762


# 3.SVC

In [33]:
from sklearn.svm import SVC

In [34]:
SVC_Classifier=SVC(kernel='rbf',degree=3)

In [35]:
SVC_Classifier.fit(xtr,ytr)

SVC()

In [36]:
ypred3=SVC_Classifier.predict(xte)

In [37]:
accuracy_score(yte,ypred3)

0.8067632850241546

In [38]:
mse=mean_squared_error(yte,ypred)
mae=mean_absolute_error(yte,ypred)
rmse=(mean_absolute_error(yte,ypred)**0.5)
r2=r2_score(yte,ypred)

In [39]:
print(mse)
print(mae)
print(rmse)
print(r2)

0.06086956521739131
0.06086956521739131
0.24671758189758447
0.7000772747762252


# 4.LogisticRegression

In [40]:
from sklearn.linear_model import LogisticRegression

In [41]:
LR_classifier=LogisticRegression()

In [42]:
LR_classifier.fit(xtr,ytr)

C:\Users\DELL\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [43]:
ypred4=LR_classifier.predict(xte)

In [44]:
ypred4

array([0, 0, 0, ..., 1, 0, 1], dtype=int64)

In [45]:
accuracy_score(yte,ypred4)

0.9632850241545894

In [46]:
mse=mean_squared_error(yte,ypred4)
mae=mean_absolute_error(yte,ypred4)
rmse=(mean_absolute_error(yte,ypred4)**0.5)
r2=r2_score(yte,ypred4)

In [47]:
print(mse)
print(mae)
print(rmse)
print(r2)

0.03671497584541063
0.03671497584541063
0.19161152325841635
0.8190942292301041
